apparmor: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Simple, elegant and feature-rich CCTV/NVR for your cameras
discovery:
- motioneye
homeassistant: 0.92.0b2
host_network: true
image: ghcr.io/hassio-addons/motioneye/{arch}
ingress: true
ingress_port: 0
ingress_stream: true
init: false
map:
- media:rw
- share:rw
- ssl
name: motionEye
options:
  action_buttons: []
  certfile: fullchain.pem
  keyfile: privkey.pem
  motion_webcontrol: false
  ssl: true
panel_icon: mdi:cctv
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
privileged:
- DAC_READ_SEARCH
- SYS_ADMIN
schema:
  action_buttons:
  - camera: int?
    command: str?
    type: list(lock|unlock|light_on|light_off|alarm_on|alarm_off|up|right|down|left|zoom_in|zoom_out|preset1|preset2|preset3|preset4|preset5|preset6|preset7|preset8|preset9)?
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  motion_webcontrol: bool
  ssl: bool
slug: motioneye
url: https://github.com/hassio-addons/addon-motioneye
version: 0.18.0
video: true
