arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: A web frontend for controlling the home
image: ghcr.io/hassio-addons/home-panel/{arch}
ingress: true
ingress_stream: true
init: false
map:
- config:rw
- ssl
name: Home Panel
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
panel_icon: mdi:home
ports:
  80/tcp: null
ports_description:
  80/tcp: Web UI (Not required for Ingress)
schema:
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
slug: home-panel
url: https://github.com/hassio-addons/addon-home-panel
version: 2.5.0
