arch:
- aarch64
- amd64
codenotary: codenotary@frenck.dev
description: Modern GPS Tracking Platform
host_network: true
image: ghcr.io/hassio-addons/traccar/{arch}
init: false
map:
- config:rw
- ssl
name: Traccar
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: false
panel_icon: mdi:car-connected
ports:
  80/tcp: 8082
ports_description:
  80/tcp: Web interface
schema:
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
services:
- mysql:want
slug: traccar
startup: services
url: https://github.com/hassio-addons/addon-traccar
version: 0.17.0
webui: '[PROTO:ssl]://[HOST]:[PORT:80]'
