arch:
- aarch64
- amd64
- armhf
- armv7
- i386
auth_api: true
codenotary: codenotary@frenck.dev
description: Browser-based log utility for Home Assistant
homeassistant: 0.92.0b2
homeassistant_api: true
image: ghcr.io/hassio-addons/log-viewer/{arch}
ingress: true
ingress_stream: true
init: false
map:
- config
- share
- ssl
name: Log Viewer
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
panel_icon: mdi:text-box-outline
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
schema:
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
slug: logviewer
url: https://github.com/hassio-addons/addon-log-viewer
version: 0.14.0
