arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Manage battery backup (UPS) devices
hassio_api: true
hassio_role: manager
homeassistant_api: true
image: ghcr.io/hassio-addons/nut/{arch}
init: false
name: Network UPS Tools
options:
  devices:
  - config: []
    driver: usbhid-ups
    name: myups
    port: auto
  mode: netserver
  shutdown_host: 'false'
  users:
  - actions: []
    instcmds:
    - all
    password: ''
    username: ''
ports:
  3493/tcp: null
ports_description:
  3493/tcp: Network UPS Tools
schema:
  devices:
  - config:
    - str
    driver: str
    name: str
    port: str
  i_like_to_be_pwned: bool?
  leave_front_door_open: bool?
  list_usb_devices: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  mode: list(netserver|netclient)
  remote_ups_host: str?
  remote_ups_name: str?
  remote_ups_password: password?
  remote_ups_user: str?
  shutdown_host: bool
  upsd_maxage: int?
  upsmon_deadtime: int?
  users:
  - actions:
    - str
    instcmds:
    - str
    password: password
    upsmon: list(master|slave)?
    username: str
slug: nut
startup: system
uart: true
udev: true
url: https://github.com/hassio-addons/addon-nut
usb: true
version: 0.11.0
